In [3]:
import numpy as np
d = 64                           # dimension
nb = 100000                      # database size
nq = 10000                       # nb of queries
np.random.seed(1234)             # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

In [8]:
xb

array([[1.91519454e-01, 6.22108757e-01, 4.37727749e-01, ...,
        6.24916732e-01, 4.78093803e-01, 1.95675179e-01],
       [3.83317441e-01, 5.38736843e-02, 4.51648414e-01, ...,
        1.51395261e-01, 3.35174650e-01, 6.57551765e-01],
       [7.53425434e-02, 5.50063960e-02, 3.23194802e-01, ...,
        3.44416976e-01, 6.40880406e-01, 1.26205325e-01],
       ...,
       [1.00811470e+02, 5.90245306e-01, 7.98893511e-01, ...,
        3.39859009e-01, 3.01949501e-01, 8.53854537e-01],
       [1.00669464e+02, 9.16068792e-01, 9.55078781e-01, ...,
        5.95364332e-01, 3.84918079e-02, 1.05637990e-01],
       [1.00855637e+02, 5.91134131e-01, 6.78907931e-01, ...,
        2.18976989e-01, 6.53015897e-02, 2.17538327e-01]], dtype=float32)

In [4]:
d

64

In [5]:
import faiss  

#faiss using product quantization for data compression and HNSW for coarse quantizer
class FAISS


# make faiss available
index = faiss.IndexFlatL2(d)   # build the index
print(index.is_trained)
index.add(xb)                  # add vectors to the index
print(index.ntotal)

True
100000


In [13]:
k = 4                          # we want to see 4 nearest neighbors
D, I = index.search(xb[:5], k) # sanity check
print(I)
print(D)
D, I = index.search(xq, k)     # actual search
print(I[:5])                   # neighbors of the 5 first queries
print(I[-5:])                  # neighbors of the 5 last queries

[[  0 393 363  78]
 [  1 555 277 364]
 [  2 304 101  13]
 [  3 173  18 182]
 [  4 288 370 531]]
[[0.        7.1751733 7.2076297 7.2511625]
 [0.        6.323565  6.684581  6.799946 ]
 [0.        5.7964087 6.3917365 7.2815123]
 [0.        7.2779055 7.527987  7.6628466]
 [0.        6.7638035 7.295121  7.368815 ]]
[[ 381  207  210  477]
 [ 526  911  142   72]
 [ 838  527 1290  425]
 [ 196  184  164  359]
 [ 526  377  120  425]]
[[ 9900 10500  9309  9831]
 [11055 10895 10812 11321]
 [11353 11103 10164  9787]
 [10571 10664 10632  9638]
 [ 9628  9554 10036  9582]]


In [7]:
I

array([[  381,   207,   210,   477],
       [  526,   911,   142,    72],
       [  838,   527,  1290,   425],
       ...,
       [11353, 11103, 10164,  9787],
       [10571, 10664, 10632,  9638],
       [ 9628,  9554, 10036,  9582]])

In [9]:
D

array([[6.815502 , 6.8894653, 7.3956795, 7.4290257],
       [6.6041145, 6.679699 , 6.72097  , 6.8286858],
       [6.4703865, 6.8578606, 7.0043755, 7.036564 ],
       ...,
       [6.0726624, 6.576721 , 6.6139526, 6.7322693],
       [6.6374817, 6.6487427, 6.8578796, 7.009613 ],
       [6.2183533, 6.4525146, 6.5487366, 6.5812836]], dtype=float32)

In [16]:
import json
import pandas as pd
import numpy as np

def retrieveData():
    url = "https://www.sec.gov/files/company_tickers.json"
    response = requests.get(url)
    json_data = response.json()
    file_name = "company_tickers.json"
    with open(file_name, "w") as json_file:
        json.dump(json_data, json_file)
    print(f"JSON data saved to {file_name}")

def loadData():
    file_name = "company_tickers.json"
    with open(file_name, "r") as json_file:
        loaded_json_data = json.load(json_file)
    df = pd.DataFrame(loaded_json_data)
    df = df.transpose()
    df.title = df.title.str.title()
    df = df.rename({"title":"companyName"},axis=1)
#     df = df[~df.ticker.str.contains('-')]
#     df = df.drop_duplicates(subset='Company', keep='first')
    df.to_csv("SEC-CompanyTicker.csv")
    return df
df = loadData()
df

cik_str   ticker                companyName
0       320193     AAPL                 Apple Inc.
1       789019     MSFT             Microsoft Corp
2      1652044    GOOGL              Alphabet Inc.
3      1018724     AMZN             Amazon Com Inc
4      1045810     NVDA                Nvidia Corp
...        ...      ...                        ...
10893  1945711    LVROW                 Lavoro Ltd
10894  1898795  LVWR-WT       Livewire Group, Inc.
10895  1837344    MBTCR  Nocturne Acquisition Corp
10896  1837344    MBTCU  Nocturne Acquisition Corp
10897  1779474    MAPSW        Wm Technology, Inc.

[10898 rows x 3 columns]